/* eslint-disable */
// This file is generated by scripts/generate-command-registry.ts
// Do not edit by hand.

import type { LazyCommandEntry } from './types.js'

export const commandRegistry: readonly LazyCommandEntry[] = [
  // add-file-to-context.ts
  {
    manifest: {
  commandId: 'babadeluxe-ai-coder.context.addFileToBabaContext',
  title: 'Add File to BabaContext™',
  menus: {
    'explorer/context': [
      {
        when: '!explorerResourceIsFolder',
        group: 'navigation@50',
      },
    ],
  },
},
    load: async () => {
      const module = await import('./add-file-to-context.js')
      return module.AddFileToContextCommand
    },
  },
  // add-folder-to-context.ts
  {
    manifest: {
  commandId: 'babadeluxe-ai-coder.context.addFolderToBabaContext',
  title: 'Add Folder to BabaContext™',
  menus: {
    'explorer/context': [
      {
        when: 'explorerResourceIsFolder',
        group: 'navigation@50',
      },
    ],
  },
},
    load: async () => {
      const module = await import('./add-folder-to-context.js')
      return module.AddFolderToContextCommand
    },
  },
  // add-selection-to-context.ts
  {
    manifest: {
  commandId: 'babadeluxe-ai-coder.context.addSelectionToBabaContext',
  title: 'Add Code to BabaContext™',
  menus: {
    'editor/context': [{ when: 'editorHasSelection', group: 'navigation@50' }],
  },
},
    load: async () => {
      const module = await import('./add-selection-to-context.js')
      return module.AddSelectionToContextCommand
    },
  },
  // clear-context-root.ts
  {
    manifest: {
  commandId: 'babadeluxe-ai-coder.clearContextRoot',
  title: 'BabaDeluxe: Clear Context Root Folder',
  icon: '$(clear-all)',
  menus: {
    'view/title': [{ when: 'view == babadeluxe-ai-coder-chat', group: 'navigation@30' }],
  },
},
    load: async () => {
      const module = await import('./clear-context-root.js')
      return module.ClearContextRootCommand
    },
  },
  // generate-commit-message.ts
  {
    manifest: {
  commandId: 'babadeluxe-ai-coder.git.generateCommitMessage',
  title: 'BabaDeluxe: Generate Commit Message',
  icon: '$(sparkle)',
  menus: {
    'scm/title': [{ when: 'scmProvider == git', group: 'navigation@10' }],
  },
},
    load: async () => {
      const module = await import('./generate-commit-message.js')
      return module.GenerateCommitMessageCommand
    },
  },
  // open-settings.ts
  {
    manifest: {
  commandId: 'babadeluxe-ai-coder.openSettings',
  title: 'BabaDeluxe: Open Settings',
  icon: '$(gear)',
  menus: {
    'view/title': [{ when: 'view == babadeluxe-ai-coder-chat', group: 'navigation@10' }],
  },
},
    load: async () => {
      const module = await import('./open-settings.js')
      return module.OpenSettingsCommand
    },
  },
  // set-context-root.ts
  {
    manifest: {
  commandId: 'babadeluxe-ai-coder.setContextRoot',
  title: 'BabaDeluxe: Set Context Root Folder',
  icon: '$(folder-opened)',
  menus: {
    'view/title': [{ when: 'view == babadeluxe-ai-coder-chat', group: 'navigation@20' }],
  },
},
    load: async () => {
      const module = await import('./set-context-root.js')
      return module.SetContextRootCommand
    },
  },
  // show-chat.ts
  {
    manifest: {
  commandId: 'babadeluxe-ai-coder.showChat',
  title: 'BabaDeluxe: Show Chat',
  icon: '$(comment-discussion)',
},
    load: async () => {
      const module = await import('./show-chat.js')
      return module.ShowChatCommand
    },
  },
]

