import fs from 'node:fs/promises'
import path from 'node:path'
import process from 'node:process'
import { parseAllCommandFiles } from './command-manifest-reader.js'

const repositoryRootDirectory = process.cwd()

const commandsDirectory = path.join(repositoryRootDirectory, 'src', 'commands')
const generatedRegistryTsPath = path.join(commandsDirectory, 'generated-registry.ts')

const ignoredBasenames = new Set([
  'helper.ts',
  'types.ts',
  'register-lazy-commands.ts',
  'registry.ts',
  'generated-registry.ts',
])

const generateTypescriptRegistry = (
  registryEntries: Awaited<ReturnType<typeof parseAllCommandFiles>>
): string => {
  const lines: string[] = []
  lines.push(
    '/* eslint-disable */',
    '// This file is generated by scripts/generate-command-registry.ts',
    '// Do not edit by hand.',
    '',
    "import type { LazyCommandEntry } from './types.js'",
    '',
    'export const commandRegistry: readonly LazyCommandEntry[] = ['
  )

  for (const entry of registryEntries) {
    lines.push(
      `  // ${entry.sourceFilename}`,
      '  {',
      `    manifest: ${entry.manifestText},`,
      '    load: async () => {',
      `      const module = await import('${entry.modulePathJs}')`,
      `      return module.${entry.commandClassName}`,
      '    },',
      '  },'
    )
  }

  lines.push(']', '')
  return `${lines.join('\n')}\n`
}

const generate = async (): Promise<void> => {
  const registryEntries = await parseAllCommandFiles({ commandsDirectory, ignoredBasenames })

  await fs.writeFile(generatedRegistryTsPath, generateTypescriptRegistry(registryEntries), 'utf8')
}

await generate()
